grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

prometheus-node-exporter:
  enabled: false